In [1]:
import pandas as pd
import numpy as np
import scipy.stats as st

One way table

In [2]:
# Data.
data = np.array([220, 215, 93,64])
eye = pd.Series(data,index=['Brown','Blue','Hazel','Green'])
eye

Brown    220
Blue     215
Hazel     93
Green     64
dtype: int32

In [3]:
# Table of proportions.
eye/eye.sum()

Brown    0.371622
Blue     0.363176
Hazel    0.157095
Green    0.108108
dtype: float64

In [5]:

st.chisquare(eye)

Power_divergenceResult(statistic=133.47297297297297, pvalue=9.650879774148268e-29)

In [6]:
my_model = len(eye)*[np.mean(eye)]
st.chisquare(f_obs=eye,f_exp = my_model)

Power_divergenceResult(statistic=133.47297297297297, pvalue=9.650879774148268e-29)

In [7]:
my_model = eye.sum()*np.array([0.40,0.33,0.15,0.12])
st.chisquare(f_obs=eye,f_exp = my_model )

Power_divergenceResult(statistic=4.06265356265356, pvalue=0.25477767063672113)

Two way table

In [8]:
data_eye = {'Brown': [68,119,26,7], 'Blue':[20,84,17,94], 'Hazel':[15,54,14,10], 'Green':[5, 29, 14,16]}
data = pd.DataFrame(data_eye,index=['Black','Brown','Red','Blonde'])
data

        Brown  Blue  Hazel  Green
Black      68    20     15      5
Brown     119    84     54     29
Red        26    17     14     14
Blonde      7    94     10     16

In [9]:
st.chi2_contingency(data)

Chi2ContingencyResult(statistic=138.28984162600824, pvalue=2.325286787098839e-25, dof=9, expected_freq=array([[ 40.13513514,  39.22297297,  16.96621622,  11.67567568],
       [106.28378378, 103.86824324,  44.92905405,  30.91891892],
       [ 26.38513514,  25.78547297,  11.15371622,   7.67567568],
       [ 47.19594595,  46.12331081,  19.95101351,  13.72972973]]))

In [10]:
data_survived = {'Yes':[122, 167, 528, 673], 'No':[203,118,178,212]}
data = pd.DataFrame(data_survived,index=['1st','2nd','3rd','Crew'])
data

      Yes   No
1st   122  203
2nd   167  118
3rd   528  178
Crew  673  212

In [11]:
st.chi2_contingency(data)

Chi2ContingencyResult(statistic=190.40110361683327, pvalue=4.999927529868003e-41, dof=3, expected_freq=array([[220.01363017, 104.98636983],
       [192.93502953,  92.06497047],
       [477.93730123, 228.06269877],
       [599.11403907, 285.88596093]]))