In [ ]:
import pandas as pd

my_data2 = [220,215,93,64,64]

eye2 = pd.Series(data=my_data2, index = ['Brown','Blue','Blue','Hazel','Green'])

eye2

eye2.unique()

eye2.nunique()

eye2.value_counts()

64     2
220    1
215    1
93     1
Name: count, dtype: int64

In [ ]:
ser = pd.Series([0,10,20,30,40], index=['a','b','c','d','e'])
ser[1]
ser['b']
ser[1:3]

/tmp/ipykernel_3592/34305438.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser[1]

b    10
c    20
dtype: int64

In [ ]:
ser1 = pd.Series([0,1,2,3,4], index= [0,1,2,3,4])
ser2 = pd.Series([0,1,2,3,4], index = [4,3,2,1,0])

ser1
ser2

ser1+ser2

ser1*ser2

ser1/ser2

ser1.sum()

ser1.median()

ser1.max()
ser1.min()
ser1.std()

ser1.sort_values()

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [ ]:
ser_height = pd.Series([160,170,180],name='height')

plus_10 = lambda x:x+10
plus_10(5)

ser_height.apply(lambda x:x+10)

0    170
1    180
2    190
Name: height, dtype: int64

In [2]:
# pd.read_csv('data_iris.csv')

# iris_df = pd.read_csv('data_iris.csv')
# type(iris_df)
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['species'] = iris.target
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [5]:
data = {'NAME':['Jake','Jennifer','Paul','Andrew'],'AGE':[24,21,25,19],'GENDER':['M','F','M','M']}
pd.DataFrame(data)

df = pd.DataFrame(data)

df.info()
df.head()

# iris_df.head()
#iris_df.tail()
#iris_df.columns
#iris_df.index
# iris_df.columns = ['Sepal_Length','Sepal_width','Petal_Length','petal_width','species']
# iris_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   NAME    4 non-null      object
 1   AGE     4 non-null      int64
 2   GENDER  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

       NAME  AGE GENDER
0      Jake   24      M
1  Jennifer   21      F
2      Paul   25      M
3    Andrew   19      M

In [ ]:
df =pd.DataFrame([['Name','Age','Sex','School'],['Tom',15,'Male','middle'],['Alice',10,'Female','elementary']])
df

df=pd.DataFrame([['Tom',15,'Male','middle'],['Alice',10,'Female','elementary']],columns=['Name','Age','Sex','School'])
df

df.index

df.index=['stu1','stu2']
df

df.index

df.columns=['student_name','years','sex2','school2']
df

df.rename(index={'stu1':'student1'})
df

df.rename(index={'stu1':'student1'},inplace=True)
df

df=df.rename(index={'stu2':'student2'})
df

df.rename(columns={'student_name':'stu_name'},inplace=True)
df

         stu_name  years    sex2     school2
student1      Tom     15    Male      middle
student2    Alice     10  Female  elementary

In [ ]:
exam_data = {'math':[90,80,70],'english':[98,89,95],'music':[85,95,100],'science':[100,90,90]}
exam_data

df = pd.DataFrame(exam_data, index=['stu1','stu2','stu3'])
df

df2=df[:]
df2.drop('stu2',inplace=True)
df2
df

df3 = df[:]
df3.drop(['stu2','stu3'],axis=0,inplace=True)   #deleting multiple rows at a time
df3
df


df4 = df[:]
df4.drop('math',axis=1,inplace=True)
df4
df

df5 = df[:]
df5.drop(['english','science'],axis=1,inplace=True)    #deleting multiple columns at a time
df5
df

/tmp/ipykernel_3592/1169771391.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop('stu2',inplace=True)
/tmp/ipykernel_3592/1169771391.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.drop(['stu2','stu3'],axis=0,inplace=True)   #deleting multiple rows at a time
/tmp/ipykernel_3592/1169771391.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4.drop('math',axis=1,inplace=True)
/tmp/ipykernel_3592/1169771391.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5.drop(['english','science'],axis=1,inplace=True)    #deleting multiple columns at a time

      math  english  music  science
stu1    90       98     85      100
stu2    80       89     95       90
stu3    70       95    100       90